#!/bin/sh

# Modify this
# LIST='list\|of\|words\|splitted\|by\|slash\|and\|pipe'
LIST="dbg!\|allow(dead_code)"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=master
fi

for FILE in $(git diff-index --name-status --cached $against -- | cut -c3-); do
    # Check if the file contains one of the words in LIST
    if grep -w $LIST $FILE; then
        echo $FILE." has one of the word you don't want to commit. Please remove it"
        exit 1
    fi
done
